# Generated by Django 3.2.12 on 2022-04-09 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapmemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_x', models.FloatField(verbose_name='X座標')),
                ('coord_y', models.FloatField(verbose_name='Y座標')),
                ('image_file_name', models.CharField(max_length=255, verbose_name='イメージファイル名')),
                ('memo', models.CharField(blank=True, max_length=512, verbose_name='メモ内容')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL, verbose_name='ユーザID')),
            ],
        ),
    ]
